### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by latne1ec** [netreconlab/parse-hipaa#56]
Hey, I am trying to upload a zip file and receive this error. [Error]: request entity too large (Code: 0, Version: 1.19.4)

Is there any way to change the max file upload size?

Btw, I used the 1 click deploy on Heroku. 

Cheers

**Comment by cbaker6** [comment]
I'm assuming you are running into this issue because this setting on the Pares-Server: https://github.com/parse-community/parse-server/blob/fded5be186952f8aab273096ba249ab82d7177bb/src/Options/Definitions.js#L327-L331

I can add a parameter to allow devs to modify it in their Heroku environment. You will either need to redeploy the button, or clone and push the updates to your Heroku repo

**Comment by latne1ec** [comment]
Thanks for the info. I will have to clone and push as I already have a live app.
